### ISSUE TITLE
Crash when take photo from Camera - Android N

### ISSUE THREAD

**Issue by andriistakhov** [Tofira/ImagePickerWithCrop#7]
Hi all
It's please add codes below, to fix problem on android N

Also @Tofira thanks for this library.

1. Add code to `AndroidManifest.xml`

```
<provider
                android:name="android.support.v4.content.FileProvider"
                android:authorities="${applicationId}.provider"
                android:exported="false"
                android:grantUriPermissions="true">
            <meta-data
                    android:name="android.support.FILE_PROVIDER_PATHS"
                    android:resource="@xml/provider_paths"/>
        </provider>
```

2. Create file `provider_paths.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
            name="external_files"
            path="." />
</paths>
```

3. Update file `CameraPickerManager.java`

```
protected void sendToExternalApp() {
        Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        mProcessingPhotoUri = getImageFileCompat();
        intent.putExtra(MediaStore.EXTRA_OUTPUT, mProcessingPhotoUri);
        activity.startActivityForResult(intent, REQUEST_CODE_SELECT_IMAGE);
    }

    private Uri getImageFileCompat() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            // https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en
            String imageName = activity.getString(R.string.app_name);
            String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(new Date());
            String imageFileName = imageName + timeStamp + "_";
            File storageDir = new File(Environment.getExternalStoragePublicDirectory(
                    Environment.DIRECTORY_DCIM), "Camera");
            try {
                File image = File.createTempFile(
                        imageFileName,  /* prefix */
                        ".jpg",         /* suffix */
                        storageDir      /* directory */
                );
                return FileProvider.getUriForFile(activity,
                        BuildConfig.APPLICATION_ID + ".provider",
                        image);
            } catch (IOException e) {
                e.printStackTrace();
            }

            return null;

        } else {
            return getImageFile();
        }
    }
```

**Comment by junaidwarsi1994** [comment]
i updated the code but it still crashes no difference:
here is my Application backstack:
10-27 07:17:17.654 26592-26592/app.invision.iugomessaging E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: app.invision.iugomessaging, PID: 26592
                                                                            java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=200, result=-1, data=Intent {  }} to activity {app.invision.iugomessaging/app.invision.iugomessaging.ui.cameramodule.TempActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
                                                                                at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
                                                                                at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
                                                                                at android.app.ActivityThread.-wrap20(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                             Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
                                                                                at app.invision.iugomessaging.utils.AppUtils$10$1$1.onImageReceived(AppUtils.java:325)
                                                                                at app.invision.iugomessaging.ui.cameramodule.TempActivity.onActivityResult(TempActivity.java:47)
                                                                                at android.app.Activity.dispatchActivityResult(Activity.java:6932)
                                                                                at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
                                                                                at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) 
                                                                                at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by andriistakhov** [comment]
Did you check WRITE permission?
